### ISSUE TITLE
TypeError: msg.replace is not a function

### ISSUE THREAD

**Issue by enel-a423831** [lykmapipo/mongoose-exists#1]
I have this error:

TypeError: msg.replace is not a function
    at MongooseError.ValidatorError.formatMessage (/usr/local/lib/node_modules/mongoose/lib/error/validator.js:65:15)
    at MongooseError.ValidatorError (/usr/local/lib/node_modules/mongoose/lib/error/validator.js:21:22)
    at validate (/usr/local/lib/node_modules/mongoose/lib/schematype.js:782:13)
    at /usr/local/lib/node_modules/mongoose/lib/schematype.js:855:5
    at /usr/local/lib/node_modules/mongoose-exists/index.js:81:19
    at /usr/local/lib/node_modules/mongoose/lib/model.js:3930:16
    at (anonymous function).call (/usr/local/lib/node_modules/mongoose/lib/query.js:3018:9)
    at Immediate.<anonymous> (/usr/local/lib/node_modules/mongoose/lib/query.js:1511:14)
    at Immediate.<anonymous> (/usr/local/lib/node_modules/mongoose/node_modules/mquery/lib/utils.js:119:16)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

I think that can be solved updating row 81 in index.js from "cb(false, error);" to "cb(false, error.message);" or "cb(false, error.toString());" 

thank you,
sandro

**Comment by mryellow** [comment]
This occurs for me with the basic examples:

```
const userSchema = new Schema({
  phone: {
    type: String,
    validate: {
      validator: function(v) {
        return /\d{3}-\d{3}-\d{4}/.test(v);
      },
      message: props => `${props.value} is not a valid phone number!`
    },
    required: [true, 'User phone number required']
  }
});
```
